vaccination/Regular/routes.py
from flask import Blueprint,redirect, request, flash, url_for, render_template
from vaccination import  bcrypt, db, app
from vaccination.Regular import  forms as Forms
from vaccination.models import  User
from flask_login import current_user, login_required
import secrets, os
from datetime import timedelta
from vaccination.models import  *

from PIL import  Image


from vaccination.Regular import ALLOWED_EXTENSIONS

regular = Blueprint('regular', __name__)

@regular.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        flash("You are already logged in, please logout to register a new account", 'info')
        return redirect(url_for('general.home'))
    title = "Create Account"

    form = Forms.Registration()

    if form.validate_on_submit():
        hash_pass = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user = User(
            id=form.id.data,
            email=form.email.data,
            phone=form.phone.data,
            password=hash_pass,
        )
        db.session.add(user)
        db.session.commit()

        flash(f'Your account has been created! Just One more step!', 'success')
        return redirect(url_for('regular.update_profile'))

    return render_template('register.html', form=form, title=title)

    # update profile details


@regular.route('/complete/profile', methods=['GET', 'POST'])
@login_required
def update_profile():
    form = Forms.Profile()
    if form.validate_on_submit():
        user = User.query.get(current_user.id)
        user.first_name = form.firstname.data
        user.last_name = form.lastname.data
        user.county = form.county.data
        user.dob = form.dob.data
        db.session.commit()
        return redirect(url_for('general.home'))

    return render_template("profile_update.html", form=form)


# Login
# View profile


@regular.route('/view', methods=['GET', 'POST'])
def view_profile():
    return render_template('view_profile.html')


# update details


@regular.route('/update-profile', methods=['GET', 'POST'])
@login_required
def edit_details():
    profile_image = ""
    if request.method == 'POST':
        if 'profile_image' not in request.files:
            flash("No file info")
            return redirect(url_for('general.home'))

        myfile = request.files['profile_image']
        # check if the file name is empty

        if myfile.filename == '':
            flash("No selected file", 'info')
            return redirect(url_for('regular.edit_details'))

        if myfile.filename and myfile.filename.split('.')[-1]  in ALLOWED_EXTENSIONS:
            enc_file = secrets.token_hex(8)
            profile_image = f'{enc_file}{myfile.filename}'
            image = Image.open(myfile)
            image.thumbnail((70, 70))

            image.save(os.path.join(app.config['UPLOAD_FOLDER'], profile_image))

        else:
            flash('File chosen is not supported', 'info')
            return redirect(url_for('regular.edit_details'))

        county = request.form.get('county')
        last_name = request.form.get('last_name')
        first_name = request.form.get("first_name")
        user = User.query.get(current_user.id)
        if user:
            user.county = county
            user.last_name = last_name
            user.first_name = first_name
            if profile_image != '':
                user.profile_image = profile_image

            db.session.commit()
            flash('Your details have been updated', 'success')

            return redirect(url_for('general.home'))

    return render_template('profile.html')


@regular.route("/user/view", methods=['GET', 'POST'])
@login_required
def view_status_user():
    if current_user.is_authenticated:

        user = User.query.get(current_user.id)

        vaccine_details = Vaccination_Detail.query.filter_by(user_id=current_user.id).first()
        if vaccine_details:

            vaccine = Vaccine.query.get(vaccine_details.vaccine_id)
            result = {}

            result['remaining'] = 0
            result['next_dose'] = None

            if vaccine.doses_req > vaccine_details.dose_count:
                result['remaining'] = vaccine.doses_req - vaccine_details.dose_count

                result['next_dose'] = vaccine_details.dose_date + timedelta(
                    vaccine_details.dose_count * vaccine.dose_time)
                print(result)
            result['first'] = vaccine_details.dose_date
            result['Vaccine'] = vaccine.name
            result['dose_req'] = vaccine.doses_req

            return render_template('User_Vacc_details.html', result=result)

    return render_template("User_Vacc_details.html")

vaccination/admin/routes.py
from flask import Blueprint, redirect, url_for, render_template, request
from flask import flash
from vaccination.admin import forms as Forms
from vaccination.models import *
from vaccination import db
from flask_login import current_user, login_required

admin = Blueprint('admin', __name__)

# admin operations
@admin.route('/admin/vaccine', methods=['GET', 'POST'])
@login_required
def add_vaccine():
    # checks if the user is admin or not
    if not current_user.is_admin:
        flash("Your authentication details restricts access to this resource", 'danger')
        return redirect(url_for('general.home'))
    form = Forms.Vaccines()
    if form.validate_on_submit():
        vaccine = Vaccine(
                          name=form.name.data.lower(),
                          origin=form.origin.data,
                          doses_req=form.doses_req.data,
                          dose_time=form.dose_time.data
                          )
        db.session.add(vaccine)
        db.session.commit()
        flash("Successfully added", 'success')
        return redirect(url_for('admin.view_vaccines'))

    return render_template('vaccine.html', form=form)


# View the vaccines being offered
@admin.route('/admin/vaccine/available', methods=['GET', 'POST'])
@login_required
def view_vaccines():
    if not current_user.is_admin:
        flash("Your authentication details restricts access to this resource", 'danger')
        return redirect(url_for('general.home'))

    vaccines = Vaccine.query.all()
    return render_template('vaccines_view.html', vaccines=vaccines)


@login_required
@admin.route('/admin/users/vacc-details', methods=['GET', "POST"])
def user_vacc_details():
    if not current_user.is_admin:
        flash("Your authentication details restricts access to this resource", 'danger')
        return redirect(url_for('general.home'))
    vaccinations = Vaccination_Detail.query.all()

    # Get all the users
    complete_profile = []

    if vaccinations:

        for details in vaccinations:
            user = User.query.get(details.user_id)
            vaccine = Vaccine.query.get(details.vaccine_id)

            if details.dose_count < Vaccine.query.get(details.vaccine_id).doses_req:
                complete_profile.append(
                    {"user": details, "Name": f"{user.first_name} {user.last_name}", "Vaccine": f"{vaccine.name}",
                     'status': False})
            else:
                complete_profile.append(
                    {"user": details, "Name": f"{user.first_name} {user.last_name}", "Vaccine": f"{vaccine.name}",
                     'status': True})
    #  To get the name of the vaccine Ill create a dict

    print(complete_profile)

    return render_template('Vaccinations.html', final_details=complete_profile)


@admin.route("/admin/vaccination/add-record", methods=['GET', "POST"])
@login_required
def add_vaccination():
    if not current_user.is_admin:
        flash("Your authentication details restricts access to this resource", 'danger')
        return redirect(url_for('genearal.home'))
    form = Forms.Search()

    # Search for the record if exits in the database
    if form.validate_on_submit():
        search = form.search.data
        print(search)

        if search:
            search_result = User.query.filter_by(id=search).first()
            if search_result:
                flash('User found, feel administer the vaccine', 'success')
                vaccines = Vaccine.query.all()
                user = search_result
                return render_template("vaccinate.html", user=user, form=form, vaccine=vaccines)
            else:
                flash("No user matching those details found, please register first", 'info')
                return render_template("vaccinate.html", user=None, form=form)
    if request.form.get('vaccinate') == 'vaccinate' and request.method == "POST":
        vaccine = request.form.get('vaccine')
        user_id = request.form.get('user_id')
        # Do validation
        # This if is checking if the user who is being vaccinated has already been given a dose
        # if so the number doses will be incremented by one otherwise, a new record is inserted into the database
        # Also check if the
        if Vaccination_Detail.query.filter_by(user_id=user_id).first():
            prev_record = Vaccination_Detail.query.filter_by(user_id=user_id).first()
            prev_vaccine = Vaccine.query.filter_by(id=prev_record.vaccine_id).first()

            if prev_vaccine.id != int(vaccine):
                flash(
                    f'Please choose {prev_vaccine.name},because {User.query.get(prev_record.user_id).first_name} received it as the first dose',
                    'danger')
                return render_template("vaccinate.html", user=User.query.get(prev_record.user_id), form=form,
                                       vaccine=Vaccine.query.all())
                #  check if the number of administered vaccines are equal to the required ones
            if prev_record.dose_count >= prev_vaccine.doses_req:
                flash("The individual is already fully vaccinated", 'info')
                return redirect(url_for("admin.add_vaccination"))
            # Uppdate the dose count
            update_vacc = Vaccination_Detail.query.get(prev_record.detail_id)
            update_vacc.dose_count = update_vacc.dose_count + 1

            db.session.commit()
            # Give a feedback if the vaccination is completed
            if prev_record.dose_count == prev_vaccine.doses_req:
                flash(f"Congratulate {User.query.get(prev_record.user_id).first_name} for being fully vaccinated",
                      'success')

            flash(f"Success, Vaccination record saved! {prev_record.dose_count} ", 'success')

            return redirect(url_for('admin.user_vacc_details'))
        new_rec = Vaccination_Detail(vaccine_id=vaccine, user_id=user_id, dose_count=1)
        db.session.add(new_rec)
        db.session.commit()
        flash("Thank you for taking your first vaccine", 'success')
        return redirect(url_for('admin.add_vaccination'))

        # detail = Vaccination_Detail(vaccine_id=vaccine, user_id=user_id, dose_count=dose_left)
        # db.session.add(detail),
        # db.session.commit()
        # flash("detail added successfully", 'success')

    return render_template("vaccinate.html", form=form)

vaccination/templates/User_Vacc_details.html
{% extends 'base.html' %}
{% block title %}
    <title>Status</title>
{% endblock %}
{% block content %}
     <div class="container ">
        {% if result %}
            {% if result.get('remaining') == 0 %}
            <div class="">
            <p class=" alert alert-success">You have fully received your JAB, Congratulations for being Patriotic</p>
              <div class="">

             <div class="shadow-sm  m-auto p-5 bg-white" style="width:40%; text-align: center" >


                 <p>Vaccine Taken : <span class="badge alert-success">{{ result.get('Vaccine').upper() }}</span> </p>
                  <p>Number of doses: <span class="badge alert-info">{{ result.get('dose_req') }}</span></p>
                  <p>Dose(s) Remaining: <span class="badge alert-info">{{ result.get('remaining') }}</span></p>
                 <p>First dose on:  <span class="badge alert-info">{{ result.get('first') }}</span></p>
                  <p>Status <span class="badge alert-success">Completed</span></p>
             </div>
             </div>
            </div>
             {% elif result.get('remaining')!=0  %}
             <div class="">
            <p class=" alert alert-warning">You are partially Vaccinated, Make effor to eliminiate COVID-19</p>
             <div class="shadow w-md-50 w-lg-25  m-auto p-5 bg-white" style=" text-align: center" >
                 <p>Vaccine Taken : <span class="badge alert-success">{{ result.get('Vaccine').upper() }}</span> </p>
                  <p>Number of doses: <span class="badge alert-info">{{ result.get('dose_req') }}</span></p>
                  <p>Dose(s) Remaining: <span class="badge alert-info">{{ result.get('remaining') }}</span></p>
                 <p>First dose on:  <span class="badge alert-info">{{ result.get('first') }}</span></p>
                  <p>Next Dose date <span class="badge alert-danger">{{ result.get('next_dose') }}</span></p>
             </div>
             </div>
             {% endif %}
            {% else %}
            <div class="">

            <p class=" alert alert-danger">You have not recieved any Vaccine that's too dangerous!</p>
            </div>
           {% endif %}


     </div>
{% endblock %}

vaccination/templates/Vaccinations.html
{% extends 'vaccine.html' %}
{% block title %}<title>Central Vaccination Registry</title>{% endblock %}
{% block content %}
<div class="container">

     {% if final_details  %}
       <table class="table table-bordered table-hover table-responsive">
           <thead>
             <tr>
                 <th>User ID</th>
                 <th>Vaccine Taken</th>
                 <th>Vaccination Status</th>
                 <th>First dose</th>
             </tr>

           </thead>
           <tbody>
             {% for user in final_details %}
                 <tr>
                 <td>{{ user.Name}}</td>
                 <td> {{ user.Vaccine }} </td>
                     {% if user.status %}
                         <td class=""><a href="#" class=" nav-link badge alert-success" disabled>Fully Vaccinated</a></td>
                     {% else %}
                        <td class=""><a href="{{ url_for("admin.add_vaccination") }}" class=" nav-link badge alert-info" disabled>Record Next dose</a></td>
                     {% endif %}

                 <td>{{ user.user.dose_date }}</td>
                 </tr>
             {% endfor %}
           </tbody>
       </table>
{% endif %}


</div>
{% endblock %}

vaccination/templates/about.html
  {% block title%} 
  <title>about us</title>
  {%endblock title%}
    {%block content%}
     
    <h1>This is what you are trained about</h1>
     
    {% endblock content%}

vaccination/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Bootstrap css -->
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"/>

    <!-- Our CSS -->
    <link  type="text/css" rel="stylesheet" href="{{ url_for('static', filename='main.css') }}"/>
    {%block title%}<title>Vaccination</title>{%endblock%}
    

  </head>
  <body>
    <nav
      class="navbar navbar-expand-lg navbar-dark"
      style="background-color: rgba(2, 2, 61, 0.445)"
    >
      <a class="navbar-brand h1 mb-o" style="margin-left: 10px" href="/home"
        >Vaccination Registry</a
      >
     
      <button
        class="navbar-toggler collapsed"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#dropdown"
        aria-controls="dropdown"
        aria-expanded="false"
        aria-label="Toggle Navigation"

      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-collapse collapse " style="margin-left:20px;" id="dropdown">
        <ul class="navbar-nav ms-auto "  >
          {%if current_user.is_authenticated %}
         <li class="nav-item"><img  class=" nav-profile " src="/static/imgs/{{ current_user.profile_image }}" alt=""></li>
          <li class="nav-item"><a href="{{ url_for('auth.logout') }}" class="nav-link">Logout</a></li>
          <li class="nav-item"><a href="{{url_for('regular.view_profile')}}" class="nav-link">View Profile</a></li>
          <li class="nav-item"><a href="{{url_for('regular.view_status_user')}}" class="nav-link">View Vaccination Status</a></li>
                 {%else%}
          <li class="nav-item"><a href="{{ url_for('regular.register') }}" class="nav-link">Register</a></li>
          <li class="nav-item"><a href="{{ url_for('auth.login') }}" class="nav-link">Login</a></li>
           {%endif%}
        </ul>
      </div>
    </nav>
    {% with messages=get_flashed_messages(with_categories=True) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="alert alert-{{ category }} alert-dismissible">
                 {{ message }}
                 <button type="button" class= "btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                 </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    <div class="container">{% block content %} {%endblock content%}</div>

    <!-- Bootstrap javascript 5.0 -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="{{url_for('static', filename='main.js')}}" rel="javascript"></script>
</body>
</html>

vaccination/templates/email_password.html
{% extends 'base.html'%}
{% block title %}
<title>Pass reset</title>
{% endblock title %}

{% block content %}
<form method="post" class='w-25 m-auto' novalidate>
    {{form.hidden_tag()}}
    <div class="form-group">
        {{form.email.label()}}
         {% if form.email.errors %}
          {{form.email(class="form-control is-invalid")}}
        <div class="invalid-feedback">
         {% for error in form.email.errors %}
             <span>{{error}}</span>
        {% endfor %}
       </div>
       {% else %}
       {{form.email(class="form-control")}}
       {% endif %}
       
    </div>

    <div class="form-group">
        {{form.submit(class="btn btn-primary btn-sm")}}
    </div>
       
</form>


{% endblock content %}

vaccination/templates/home.html
{%extends 'base.html'%} {%block title%}<title>home</title> {%endblock title%}
{%block content%}

<div class="w-50 m-auto">
   <div class="mt-5">
       <img class="img-profile " src="/static/imgs/{{ current_user.profile_image }}" alt="profile">
       <p>Name <span  class="  text-danger badge alert-danger  ">{{ current_user.first_name }} {{ current_user.last_name }}</span></p>
       <p>Email Address <span class="  text-danger badge alert-danger  ">{{ current_user.email }} </span></p>
       {% if current_user.is_admin %}
       <p class="badge alert-info">Admin</p>
       {% else %}
       <p class="badge alert-info">Regular</p>
       {% endif %}
   </div>
 
</div>

{%endblock content%}

vaccination/templates/login.html
{% extends 'base.html' %} {% block title %}<title>{{ title }}</title>{% endblock
title %} {% block content %}
 <div style="width:350px; margin: 10% auto; " class=" border p-2">
   <h4>Login To View Status & more</h4>
<form method="POST" novalidate>
  {{ form.hidden_tag() }}

  <div class="form-group ">
    {{ form.id.label(class='') }}
      {% if form.id.errors %}
          {{ form.id(class='form-control is-invalid', placeholder="someone@yahoo.com", autofocus='true')}}
          {% for error in form.id.errors %}
              <div class="invalid-feedback">
                <span>{{ error }}</span>
              </div>
            {% endfor %}
          {% else %}
          {{ form.id(class='form-control', placeholder="someone@yahoo.com", autofocus='true')}}
       {% endif %}

  </div>

  <div class="form-group">
    {{ form.password.label(class='') }}
      {% if form.password.errors %}
          {{ form.password(class=' is-invalid form-control')}}
          {% for error in form.password.errors %}
           <div class="invalid-feedback"><span>{{ error }}</span></div>
          {% endfor %}
       {% else %}
        {{ form.password(class='form-control')}}
      {% endif %}
  </div>
    <div class="form-group">
     {{ form.remember(class='')
    }}
        {{ form.remember.label() }}
  </div>

<div class="form-group">
     {{ form.submit(class='btn btn-primary form-control')
    }}
  </div>
    <div>Not registered yet? <a style="text-decoration: none;"href="{{ url_for('regular.register') }}">Signup now!</a></div>

<div><a style="text-decoration: none;"href="{{ url_for('auth.request_pass_reset_token') }}">Forgot password? </a></div>
</form>
    </div>
{% endblock %}

vaccination/templates/profile.html
{% extends 'base.html' %} {% block title %}<title>Edit Info</title>{% endblock
%} {% block content %}

<div class="w-50 m-auto">
  <form method="post" action="{{url_for('regular.edit_details')}}" enctype="multipart/form-data">
    <div class="d-flex flex-column justify-content-center align-items-center">
      <h3>Update Details</h3>
      <div class="image-container">
        <img
          class="img-profile"
          src="static/imgs/{{ current_user.profile_image }}"
          alt=""
        />
      </div>
    </div>
    <div class="form-group">
      <label for="">Name</label>
      <input
        name="first_name"
        type="text"
        class="form-control editable"
        value="{{current_user.first_name}}"
      />
    </div>
    <div class="form-group">
      <label for="">Other Names</label>
      <input
        name="last_name"
        type="text"
        class="form-control editable"
        value="{{current_user.last_name}}"
      />
    </div>

    <div class="form-group">
      <label for="">Region Located</label>
      <input
        name="county"
        type="text"
        class="form-control editable"
        value="{{current_user.county}}"
      />
    </div>
     <div class="form-group">
      <label for="">Profile Photo</label>
      <input
        name="profile_image"
        type="file"
        class="form-control editable"
        
      />
    </div>
    <div class="d-flex justify-content-around">
      <button id="btn-edit" type="button" class="btn btn-primary btn-sm">
        Edit Info
      </button>
      <button
        id="btn-save"
        type="submit"
        style="display: none"
        class="btn btn-sm btn-primary"
      >
        Save Changes
      </button>
    </div>
  </form>
</div>

{% endblock %}

vaccination/templates/profile_update.html
{%extends 'base.html'%}

{%block title%}
<title>Update profile</title>
 {%endblock title%}
 {%block content%} 
  <form method="post" novalidate class="w-50 m-auto">
      <h4 class="text-center">Complete Profile</h4>
      {{form.hidden_tag()}}
      <div class="form-group">
          {{form.firstname.label()}}
          {% if form.firstname.errors %}
            {{form.firstname(class="form-control is-invalid")}}
            {% for error in form.firstname.errors %}
            <div class="invalid-feedback">
                {{error}}
            </div>
            {%endfor%}

            {%else%}
            {{form.firstname(class="form-control")}}
            
            {%endif%}
      </div> 
       <div class="form-group">
          {{form.lastname.label()}}
          {% if form.lastname.errors %}
            {{form.lastname(class="form-control is-invalid")}}
            {% for error in form.lastname.errors %}
            <div class="invalid-feedback">
                {{error}}
            </div>
            {%endfor%}
            {%else%}
            {{form.lastname(class="form-control")}}
            
            {%endif%}
      </div> 
       <div class="form-group datepicker">
          {{form.dob.label()}}
          {% if form.dob.errors %}
            {{form.dob(class="form-control is-invalid ")}}
            {% for error in form.dob.errors %}
            <div class="invalid-feedback">
                {{error}}
            </div>
            {%endfor%}
            {%else%}
            {{form.dob(class="form-control datepicker")}}
            
            {%endif%}
      </div> 
       <div class="form-group">
          {{form.county.label()}}
          {% if form.county.errors %}
            {{form.county(class="form-control is-invalid")}}
            {% for error in form.county.errors %}
            <div class="invalid-feedback">
                {{error}}
            </div>
            {%endfor%}
            {%else%}
            {{form.county(class="form-control")}}
            
            {%endif%}
      </div> 
      <div class="form-group">
          {{form.complete(class="form-control btn btn-primary")}}
      </div>
  </form>
 {%endblock content%}

vaccination/templates/register.html
{% extends 'base.html' %} {% block title %}<title>{{ title }}</title>{% endblock
title %} {% block content %}
 <div style="width:350px; margin: 20px auto;" class=" border form-wrap">
   <h4 class="">Fill the form To Register</h4>
<form method="POST" novalidate>
  {{ form.hidden_tag() }}
  <div class="form-group">
  {#  The code blow is for form validation feedback using bootstrap classes#}
    {{ form.id.label(class='') }}
      {% if form.id.errors %}
           {% for error in form.id.errors %}
                {{ form.id(class='form-control is-invalid', placeholder="e.g. 123456789", autofocus='true')}}
                  <div class="invalid-feedback"><span>{{ error}}</span></div>
           {% endfor %}
          {% else %}
          {{ form.id(class='form-control',placeholder="e.g. 123456789", autofocus='true')}}
      {% endif %}

  </div>
  <div class="form-group">
    {{ form.email.label(class='') }}
      {% if form.email.errors %}

          {{ form.email(class='form-control is-invalid', placeholder="someone@yahoo.com")}}

          {% for error in form.email.errors %}
               <div class="invalid-feedback">
                 <span>{{ error }}</span>
               </div>
            {% endfor %}
         {% else %}
           {{ form.email(class='form-control', placeholder="someone@yahoo.com")}}
       {% endif %}

  </div>
  <div class="form-group">
    {{ form.phone.label(class='') }}
      {% if form.phone.errors %}
          <div class="input-group">
          <span class="input-group-text">+254</span>
           {{ form.phone(class='is-invalid form-control')}}
          {% for error in form.phone.errors %}
              <div class="invalid-feedback"><span>{{ error }}</span></div>
          {% endfor %}
           </div>


      {% else %}
          <div class="input-group">
          <span class="input-group-text">+254</span>
           {{ form.phone(class='form-control')}}
           </div>

      {% endif %}


  </div>
  <div class="form-group">
    {{ form.password.label(class='') }}
      {% if form.password.errors %}
         {{ form.password(class='form-control is-invalid')}}
          {% for error in form.password.errors %}
              <div class="invalid-feedback">
                <span>{{ error }}</span>
              </div>
           {% endfor %}
          {% else %}
          {{ form.password(class='form-control')}}
       {% endif %}

  </div>
  <div class="form-group">
{#  The code blow is for form validation feedback using bootstrap classes#}
   {{ form.confirm.label(class='') }}
      {% if form.confirm.errors %}
         {{ form.confirm(class='form-control is-invalid')}}
          {% for error in form.confirm.errors %}
              <div class="invalid-feedback">
                <span>{{ error }}</span>
              </div>
           {% endfor %}
          {% else %}
          {{ form.confirm(class='form-control')}}
       {% endif %}

  </div>
<div class="form-group">
     {{ form.submit(class='btn btn-primary form-control')
    }}
  </div>
  <div>
      <p>Already Registered? <a style="text-decoration: none" href="{{ url_for('auth.login') }}">Login</a></p>
  </div>
</form>
    </div>
{% endblock %}

vaccination/templates/vaccinate.html
{% extends 'vaccine.html' %}
{% block title %}<title>Add Vaccination</title>{% endblock %}
{% block content %}
  <h3 class="text-center   alert-info">Record Vaccination</h3>
    <div class="container">
    <form class="d-flex justify-content-end " method="POST" action="/admin/vaccination/add-record">
        {{ form.hidden_tag() }}
     <div class="form-group  " style="margin-right:10px;">
         {{ form.search(class="form-control") }}
     </div>
       {{ form.btnsearch(class="btn btn-sm btn-secondary ") }}
    </form>
        {% if user %}
            <form action="{{ url_for('admin.add_vaccination') }}" method="post" class="w-25 m-auto">
            <div class="form-group m-2">
             <label for="">Name on File</label>   <input class="form-control" type="text" disabled value="{{ user.first_name  }} {{ user.last_name }}">

          </div>
            <div class="form-group m-2" >
            <label>National ID number</label><input class="form-control " name="user_id" type="text" value="{{ user.id}}" />
            </div>
            <div class="form-group m-2">
                <label for="vaccine">Vaccine Administered</label>
                <select name="vaccine" class="form-control" id="vaccine">
                    {% if vaccine %}
                        {% for vac in vaccine %}
                            <option value="{{ vac.id }}">{{ vac.name }}</option>
                        {% endfor %}
                        {% endif %}
                </select>
            </div>
            <div class="form-group m-2">
         <button class="btn form-control btn-block btn-sm btn-success" value="vaccinate" type="submit" name="vaccinate">Submit</button>
     </div>
      </form>
        {% endif %}

    </div>

{% endblock %}

vaccination/templates/vaccines_view.html
{% extends 'vaccine.html' %}
{% block title %}
    <title>Currenty offered vaccines</title>
{% endblock title %}
{% block content %}


    {% if vaccines %}
        <h3 class="text-center">Vaccines Currently on Offer</h3>
          <div class="container">

            <table class="table table-bordered table-hover">
                <thead>
                  <tr>
                      <th>Count</th>
                       <th>Name</th>
                      <th>Country</th>
                      <th>Doses Required</th>
                      <th>Time Apart</th>
                  </tr>
                 </thead>
                <tbody>
                 {% for vaccine in vaccines %}
                  <tr>
                      <td>{{ vaccine.id }}</td>
                      <td>{{vaccine.name}}</td>
                      <td>{{ vaccine.origin }}</td>
                      <td>{{ vaccine.doses_req }}</td>
                      <td>{{ vaccine.dose_time }}</td>
                  </tr>
                {% endfor %}
                </tbody>
            </table>

           </div>

        {% else %}

          <h3  style="margin-right:auto; margin-left:auto; margin-top:30vh;" class="alert alert-danger   w-50">No vaccines available now, Click  <a style="text-decoration: none;" class="text-success" href="{{ url_for('admin.add_vaccine') }}">Here</a> to add</h3>

    {% endif %}

{% endblock content %}